name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      AV_API_KEY: ${{ secrets.AV_API_KEY }}
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Outline Client
      run: |
        curl -L -o Outline-Client.AppImage https://s3.amazonaws.com/outline-releases/client/linux/stable/Outline-Client.AppImage
        chmod +x Outline-Client.AppImage

    - name: Start VPN using Outline
      env:
        OUTLINE_ACCESS_KEY: ${{ secrets.OUTLINE_ACCESS_KEY }}
      run: |
        ./Outline-Client.AppImage -a $OUTLINE_ACCESS_KEY &

    - name: Wait for VPN connection
      run: sleep 10  # Дождитесь подключения к VPN

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python test_main.py
