name: Run Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: self-hosted
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
      AV_API_KEY: ${{ secrets.AV_API_KEY }}
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python test_main.py
